---
name: "Deploy Infra"

on:
  workflow_dispatch:

jobs:
  deploy-infra:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TERRAFORM_VERSION: "1.12.2"
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4

      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform init
        run: terraform init
        working-directory: ./

      - name: Terraform validate
        run: terraform validate
        working-directory: ./

      - name: Terraform plan
        run: terraform plan
        working-directory: ./

#      - name: Terraform apply
#        run: terraform apply --auto-approve
#        working-directory: ./infra/
